;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	comment-dwim
	electric-pair-delete-pair
	electric-verilog-semi
	electric-verilog-tab
	end-of-visual-line
	helm-find-files
	indent-for-tab-command
	kill-region
	kill-visual-line
	move-to-window-line-top-bottom
	org-beginning-of-line
	org-cycle
	org-end-of-line
	org-export-dispatch
	org-force-self-insert
	org-open-line
	org-return-and-maybe-indent
	org-self-insert-command
	org-yank
	overwrite-mode
	paredit-forward-slurp-sexp
	paredit-kill
	paredit-open-round
	slime-autodoc-space
	))

(setq mc/cmds-to-run-once
      '(
	cider-eval-defun-at-point
	elpy-shell-send-region-or-buffer
	switch-window
	))
