#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# rules
bspc rule -a Emacs state=tiled

bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr

xset fp+ ~/.fonts/misc &
picom --config $HOME/.config/picom/picom.conf 
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
